name: Sync Wiki from wiki-src

on:
  push:
    branches:
      - main
    paths:
      - 'wiki-src/**'

jobs:
  sync-wiki:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Push to Wiki
      uses: SwiftDocOrg/github-wiki-publish-action@v1
      with:
        path: wiki-src
      env:
        GH_PERSONAL_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
