name: Sync Wiki from root

on:
  push:
    branches:
      - main
    paths:
      - '**/*.md'        # Detecta cambios en cualquier .md en la raíz o subcarpetas

permissions:
  contents: write
  issues: read

jobs:
  sync-wiki:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main repo
        uses: actions/checkout@v3

      - name: Clone wiki and sync content
        run: |
          git clone https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.wiki.git wiki

          # Copiar todos los archivos markdown de la raíz a la carpeta wiki
          cp *.md wiki/ || echo "No markdown files in root"

          cd wiki

          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"

          git status
          git diff --staged || echo "No changes staged"
          git add .

          git commit -m "Sync wiki from repo root" || echo "No changes to commit"

          git push origin master

