name: Sync Wiki from wiki-src

on:
  push:
    branches:
      - main
    paths:
      - 'wiki-src/**'

permissions:
  contents: write
  issues: read

jobs:
  sync-wiki:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main repo
        uses: actions/checkout@v3

      - name: Clone wiki and sync content
        run: |
          git clone https://github.com/${{ github.repository }}.wiki.git wiki
          cp -r wiki-src/* wiki/
          cd wiki
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git add .
          git commit -m "Sync wiki from wiki-src" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.wiki.git HEAD:master
