name: Sync Wiki from wiki-src

on:
  push:
    branches:
      - main
    paths:
      - 'wiki-src/**'

permissions:
  contents: write
  issues: read

jobs:
  sync-wiki:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main repo
        uses: actions/checkout@v3

      - name: Clone wiki and sync content
        run: |
          # Clonar wiki en carpeta local wiki
          git clone https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.wiki.git wiki

          # Copiar y reemplazar todos los archivos desde wiki-src a wiki
          cp -r wiki-src/* wiki/

          cd wiki

          # Configurar git para commits
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"

          # Mostrar estado para debug
          git status

          # Agregar cambios
          git add .

          # Mostrar diferencias para debug
          git diff --staged || echo "No changes staged"

          # Hacer commit solo si hay cambios
          git commit -m "Sync wiki from wiki-src" || echo "No changes to commit"

          # Empujar cambios a la rama master de la wiki
          git push origin master
