name: Actualizar sección de repositorios en README

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y jq

      - name: Obtener lista de repositorios y actualizar README
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_USER: JaimeCamachoDev
        run: |
          curl -s -H "Authorization: token $GITHUB_TOKEN" "https://api.github.com/users/$GITHUB_USER/repos?per_page=100" > repos.json
          cat repos.json | jq '.' || echo "Failed to parse JSON"

          repos=$(cat repos.json | jq -r '.[] | "- [\(.name)](https://github.com/'$GITHUB_USER'/\(.name)) – \(.description // "Breve descripción")"')
          if [ -z "$repos" ]; then
            echo "No repositories found or API call failed."
            exit 1
          fi

          echo "Lista de repos:"
          echo "$repos"

          if [ ! -f README.md ]; then
            echo "README.md not found, creating a new one."
            echo "## Repositorios y Proyectos Destacados" > README.md
          fi

          sed -i '/## Repositorios y Proyectos Destacados/,/## /c\
          ## Repositorios y Proyectos Destacados\n\n'"$repos"'\n' README.md || {
            echo "Failed to update README.md with sed."
            exit 2
          }

      - name: Commit y push cambios
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "Actualizar sección de repositorios en README" || echo "Sin cambios"
          git push
