name: Actualizar sección de repositorios en README

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install jq
        run: sudo apt-get install -y jq

      - name: Obtener lista de repositorios y actualizar README
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_USER: JaimeCamachoDev
        run: |
          response=$(curl -s -H "Authorization: token $GITHUB_TOKEN" "https://api.github.com/users/$GITHUB_USER/repos?per_page=100")
          if echo "$response" | jq empty 2>/dev/null; then
            repos=$(echo "$response" | jq -r --arg user "$GITHUB_USER" '.[] | "- [\(.name)](https://github.com/\($user)/\(.name)) – \(.description // "Breve descripción.")"')
          else
            echo "Error: Invalid JSON response"
            exit 1
          fi

          echo "Lista de repos:"
          echo "$repos"

          tmpfile=$(mktemp)
          echo "$repos" > "$tmpfile"

          # Reemplaza la sección con solo el encabezado (sin \n)
          sed -i '/## Repositorios y Proyectos Destacados/,/## /c## Repositorios y Proyectos Destacados' README.md

          # Inserta la lista justo después del encabezado
          sed -i "/## Repositorios y Proyectos Destacados/r $tmpfile" README.md

          rm "$tmpfile"

      - name: Commit y push cambios
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "Actualizar sección de repositorios en README" || echo "Sin cambios"
          git push
