name: Actualizar sección de repositorios en README

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Obtener lista de repositorios y actualizar README
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_USER: JaimeCamachoDev
        run: |
          repos=$(curl -s -H "Authorization: token $GITHUB_TOKEN" "https://api.github.com/users/$GITHUB_USER/repos?per_page=100" | jq -r '.[] | "- [\(.name)](https://github.com/'$GITHUB_USER'/\(.name)) – Breve descripción."')

          echo "Lista de repos:"
          echo "$repos"

          # Reemplazar la sección en README.md con sed
          sed -i '/## Repositorios y Proyectos Destacados/,/## /c\
## Repositorios y Proyectos Destacados\n\n'"$repos"'\n' README.md

      - name: Commit y push cambios
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "Actualizar sección de repositorios en README" || echo "Sin cambios"
          git push
